config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'page/home'
  post '/home' => 'page#addtag', :as => "addtag"
  delete '/home.:tag' => 'page#removetag', :as => "removetag"
  root 'page#home'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  acts_as_taggable # Alias for acts_as_taggable_on :tags
  acts_as_taggable_on :words

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  #before_action :authenticate_user, only: [:contact]

  def home
    if user_signed_in?
      @user = current_user
      
    else #user don't sign in, do nothing

    end
  end

  def addtag
    @user = current_user
    @input = params[:words]
    Rails.logger.debug("+++++++++++++++++  input: #{@input.inspect}")
    
    @tag = @user.word_list.add(@input)
    Rails.logger.debug("-----------------  tag: #{@tag.inspect}")
    @user.save
    @user.reload
    
    render :home
  end

  def removetag
    @user = current_user
    @input = params[:tag]
    Rails.logger.debug("+++++++++++++++++  input: #{@input.inspect}")
    
    @tag = @user.word_list.remove(@input)
    #Rails.logger.debug("-----------------  tag: #{@tag.inspect}")
    @user.save
    @user.reload
    
    render :home
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/page/home.html.erb
<head>
  <style>
    #word {
      width:20%;
      float:left;	      
    }
    #transfer {
      width:80%;
      height:500px;
      float:left;
    }
  </style>
</head>

<body>
  <% if user_signed_in? %>  
    <%= link_to "登出", destroy_user_session_path, method: :delete  %>

    <%= form_tag addtag_path do %>
      <%= text_field_tag :words%>
      <%= submit_tag%>
    <% end %>

    <div id = "word">
      <table>
        <% @user.word_list.each do |word| %>
          <tr>
            <td> # </td>
            <td>
                <a href= <%= "http://dictionary.cambridge.org/zht/"\
                    + "%E8%A9%9E%E5%85%B8/"\
                    + "%E8%8B%B1%E8%AA%9E-%E6%BC%A2%E8%AA%9E-%E7%B9%81%E9%AB%94/"\
                    + word%> target="iframe_a"> 
                <%= word %> </a>
            </td>
            <td> <%= link_to("Delete", removetag_path(word), :class => "btn btn-mini", \
                :method=>:delete,:confirm=>"Areyousure?")%>
            </td> 
          </tr>
          <% end %> 
      </table>
    </div>
    <div id = "transfer">
      <iframe width="100%" height="100%" src="http://dictionary.cambridge.org/zht/" name="iframe_a">
      </iframe>
    </div>

  <% else %>
    <%= link_to "登入", new_user_session_path %>
    <%= link_to "註冊", new_user_registration_path %>
  <% end %>

</body>